# -*- coding: utf-8 -*-
"""Pentagon numbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gTyVlEtVmyQ_HlGN-IrlzjR1O9jPXsWU
"""

import numpy as np
import itertools

def func(n):
   return n*(3*n-1)//2

def sum_diff(n_1,n_2):
  return [(3*(n_1**2 + n_2**2) - (n_1 + n_2))//2,(3*(n_2**2 - n_1**2) - (n_2 - n_1))//2]

from time import time
start = time()

Gate = False
S = [func(i) for i in range(1,6000)]
for i in range(1000,5000):
  for j in range(i,5000):
    A,B = sum_diff(i,j)
    if (A in S) & (B in S):
      Gate = True
      print(B)
      break
  if Gate:
    break

end = time()
print("time taken : " + str(end-start) + "s")

