# -*- coding: utf-8 -*-
"""Self powers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OwXoatHPq03UYbda4lKclX5VTWKNct2u
"""

from math import pow

Sum = 0
for i in range(1,1000):
  try :
    if len(str(i**i)) > 10:
      Sum += int(str(int(i**i))[-10:])
    else:
      Sum += int(i**i)
    
    if len(str(Sum)) > 10:
      Sum = int(str(Sum)[-10:])
  except OverflowError:
    print(i)

Sum